# Generated by Django 2.0.5 on 2018-05-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityID', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityID', models.CharField(max_length=3)),
                ('hotelID', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
    ]
